// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoBase.API.Data;

#nullable disable

namespace PhotoBase.API.Data.Migrations
{
    [DbContext(typeof(PhotoBaseDbContext))]
    [Migration("20260307061205_AddUsersAndAuth")]
    partial class AddUsersAndAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhotoBase.API.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@photobase.dev",
                            PasswordHash = "$2a$11$44UQM/pnhwMoey1LSCNv9epsndc2osuM0APKUkWZZPiK6VO6.SYsu",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@photobase.dev",
                            PasswordHash = "$2a$11$4VyCAySzrJpUJH9guI4dPuPOWQHie7b85mjsVCEzo21imdTGXf7yO",
                            Role = "Internal"
                        });
                });

            modelBuilder.Entity("PhotoBase.API.Entities.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Categories")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Keywords")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Photographer")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ThumbPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber")
                        .HasDatabaseName("IX_ImageAssets_AccessionNumber");

                    b.HasIndex("HashSha256")
                        .HasDatabaseName("IX_ImageAssets_HashSha256");

                    b.ToTable("ImageAssets", (string)null);
                });

            modelBuilder.Entity("PhotoBase.API.Entities.PlantRecord", b =>
                {
                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CollectionTrip")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AccessionNumber");

                    b.ToTable("PlantRecords", (string)null);

                    b.HasData(
                        new
                        {
                            AccessionNumber = "2024-0001",
                            CollectionTrip = "Spring 2024 East Asia",
                            Location = "Garden A - Section 3",
                            PlantName = "Magnolia zenii",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AccessionNumber = "2024-0002",
                            CollectionTrip = "Fall 2023 Appalachian",
                            Location = "Garden B - Oak Collection",
                            PlantName = "Quercus alba",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AccessionNumber = "2024-0003",
                            Location = "Garden C - Japanese Maples",
                            PlantName = "Acer palmatum",
                            UpdatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PhotoBase.API.Entities.ImageAsset", b =>
                {
                    b.HasOne("PhotoBase.API.Entities.PlantRecord", "PlantRecord")
                        .WithMany("ImageAssets")
                        .HasForeignKey("AccessionNumber")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlantRecord");
                });

            modelBuilder.Entity("PhotoBase.API.Entities.PlantRecord", b =>
                {
                    b.Navigation("ImageAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
